version: "3.9"

services:
  fe:
    build: ./web-platform
    volumes:
      - ./web-platform:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    working_dir: /app
    env_file: [.env]
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev", "--", "--port", "3000"]

  be:
    platform: linux/amd64
    build: ./service-platform
    volumes:
      - ./service-platform:/app
    ports:
      - "8001:8001"
    working_dir: /app
    env_file: [.env]
    entrypoint: ["poetry", "run"]
    command: ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "8001"]
